# See https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
      timezone: 'Europe/Berlin'
    open-pull-requests-limit: 10
    commit-message:
      prefix: 'deps'
    labels:
      - 'dependencies'
    target-branch: 'develop'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
      timezone: 'Europe/Berlin'
    open-pull-requests-limit: 10
    commit-message:
      prefix: 'ci-actions'
    labels:
      - 'ci-actions'
    target-branch: 'develop'
